apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Standalone Training Operator for TFJob, PyTorchJob, etc.
  - github.com/kubeflow/training-operator/manifests/overlays/standalone?ref=v1.8.1

namespace: kubeflow