apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # This is the "secret sauce" for low-RAM setups: 
  # It installs KFP without the Google Cloud dependencies
  - github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=2.2.0
  - github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=2.2.0

namespace: kubeflow